export const adminData = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    totalPoints: 85,
    submitDate: "15 Ιανουαρίου 2023",
    scientificField: "Τουρισμός",
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    submitDate: "16 Ιανουαρίου 2023",
    scientificField: "Αγγλικά",
    totalPoints: 92,
  },
  {
    id: 3,
    firstName: "Alice",
    lastName: "Johnson",
    totalPoints: 78,
    submitDate: "17 Ιανουαρίου 2023",
    scientificField: "Μαθηματικά",
  },
];

export const applicantData = {
  firstName: "John",
  lastName: "Doe",
  email: "adsf@example.com",
  phdTitle: "Machine Learning in Education",
  phdAcquisitionDate: "2022-05-15",
  scientificField: "Τουρισμός",
  workExperience: "2",
  coursePlanRelevancePoints: 20,
  courseMaterialStructurePoints: 3,
  thesisRelevancePoints: 17,
  paperPoints: 10,
  workExperiencePoints: 10,
  notPastProgramPoints: 5,
  totalPoints: 85,
  papers: [
    {
      id: 1,
      type: "journal",
      paperTitle: "Advanced Tourism Management Strategies",
      journalConfTitle: "International Journal of Tourism Research",
      year: "2023",
      issn: "1473-8298",
      country: "Greece",
      quartile: "Q1",
      points: 5,
    },
    {
      id: 2,
      type: "conference",
      paperTitle: "Innovative Approaches in Tourism",
      journalConfTitle: "Proceedings of the International Conference on Tourism",
      year: "2021",
      issn: "1234-5678",
      country: "Greece",
      quartile: "Q2",
      points: 2,
    },
    {
      id: 3,
      type: "journal",
      paperTitle: "Cultural Heritage and Sustainable Tourism",
      journalConfTitle: "Journal of Cultural Heritage Management and Sustainable Development",
      year: "2020",
      issn: "2044-1266",
      country: "Greece",
      quartile: "Q3",
      points: 4,
    },
    {
      id: 4,
      type: "journal",
      paperTitle: "Tourism Economics and Policy",
      journalConfTitle: "Tourism Economics",
      year: "2022",
      issn: "1464-6669",
      country: "Greece",
      quartile: "Q1",
      points: 6,
    },
    {
      id: 5,
      type: "journal",
      paperTitle: "Digital Transformation in Tourism",
      journalConfTitle: "Journal of Tourism and Digital Transformation",
      year: "2023",     
      issn: "1234-5678",
      country: "Greece",
      quartile: "Q1",
      points: 3,
    },
  ],
};

export const legacyUser = {
  id: 1,
  firstName: "Test",
  lastName: "User",
  role: "applicant", // Changed to admin to test auto-fill
  email: "test@test.com",
  name: "Test User",
  // Add form data for auto-fill testing
  form: {
    firstName: "Test",
    lastName: "User",
    email: "test@test.com",
    scientificField: "Τουρισμός",
    phdAcquisitionDate: "2021-06-15",
    phdInstitution: "Πανεπιστήμιο Πατρών",
    phdTitle: "Machine Learning Applications in Education",
    workExperience: "3",
    hasNotParticipatedInPastProgram: true,
    militaryObligations: "completed",
    coursePlanRelevance:
      "Το σχεδιάγραμμα διδασκαλίας βασίζεται στις σύγχρονες μεθοδολογίες της πληροφορικής...",
    courseMaterialStructure:
      "Η δομή του μαθήματος περιλαμβάνει εργαστηριακές ασκήσεις και θεωρητικές ενότητες...",
    thesisRelevance:
      "Η διδακτορική διατριβή εστιάζει στη χρήση τεχνητής νοημοσύνης στην εκπαίδευση...",
    bio: "Είμαι διδάκτορας Πληροφορικής με εξειδίκευση στη μηχανική μάθηση και την εκπαιδευτική τεχνολογία...",
    // File names from backend (these will be displayed as already uploaded)
    cvDocument: "cv_test_user.pdf",
    phdDocument: "phd_diploma_test_user.pdf",
    doatapDocument: "doatap_recognition_test_user.pdf",
    militaryObligationsDocument: "military_declaration_test_user.pdf",
    coursePlanDocument: "course_plan_test_user.pdf",
    papers: [
      {
        type: "journal",
        paperTitle: "AI in Educational Systems",
        journalConfTitle: "Journal of Educational Technology",
        year: "2013",
        issn: "1234-5678",
      },
      {
        type: "journal",
        paperTitle: "Machine Learning for Student Assessment",
        journalConfTitle: "Computers & Education",
        year: "2015",
        issn: "0360-1315",
      },
    ],
  },
};
